/* E8820s */

#define BOARD_PID		"E8820s"
#define BOARD_NAME		"E8820s"
#define BOARD_DESC		"E8820s Wireless Router"
#define BOARD_VENDOR_NAME	"ZTE Technology"
#define BOARD_VENDOR_URL		"http://www.zte.com.cn/"
#define BOARD_MODEL_URL		"http://www.zte.com.cn/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	80
#define BOARD_GPIO_BTN_FN1	10
#define BOARD_GPIO_BTN_RESET	18
#define BOARD_GPIO_BTN_WPS	8
#undef  BOARD_GPIO_LED_ALL
#undef	BOARD_GPIO_LED_WIFI	
#define BOARD_GPIO_LED_SW2G	14
#define BOARD_GPIO_LED_SW5G	16
#define BOARD_GPIO_LED_POWER	31
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	3
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	2
#define BOARD_NUM_ANT_5G_RX	2
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#undef BOARD_GPIO_PWR_USB
#undef BOARD_GPIO_PWR_USB_ON
#define BOARD_USB_PORT_SWAP	0
